export const TOGGLE_DEVICE = 'TOGGLE_DEVICE'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const EXPAND_MENU = 'EXPAND_MENU'

export const SWITCH_EFFECT = 'SWITCH_EFFECT'

// Results

export const RESULTS_PUSH = 'RESULTS_PUSH'
export const RESULTS_CLEAR = 'RESULTS_CLEAR'
export const RESULTS_CHANGED = 'RESULTS_CHANGED'

// Dashboard

export const SOCKET_DASHBOARD = 'SOCKET_DASHBOARD'
export const SOCKET_DASHBOARD_UPDATE_TILE = 'SOCKET_DASHBOARD_UPDATE_TILE'

// Home Charts

export const SOCKET_CHART_UI = 'SOCKET_CHART_UI'
export const SOCKET_CHART_INSTALLER = 'SOCKET_CHART_INSTALLER'
export const SOCKET_CHART_REST = 'SOCKET_CHART_REST'
export const SOCKET_CHART_UI_CHANGED = 'SOCKET_CHART_UI_CHANGED'
export const SOCKET_CHART_INSTALLER_CHANGED = 'SOCKET_CHART_INSTALLER_CHANGED'
export const SOCKET_CHART_REST_CHANGED = 'SOCKET_CHART_REST_CHANGED'

// Configs

export const SOCKET_CONFIGS = 'SOCKET_CONFIGS'
export const SOCKET_CONFIGS_UPDATE = 'SOCKET_CONFIGS_UPDATE'

// Build

export const SOCKET_BUILD = 'SOCKET_BUILD'

// Time sync

export const SOCKET_TIME_SYNC = 'SOCKET_TIME_SYNC'
