export const TOGGLE_DEVICE = 'TOGGLE_DEVICE'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const EXPAND_MENU = 'EXPAND_MENU'

export const SWITCH_EFFECT = 'SWITCH_EFFECT'

// Results

export const RESULTS_PUSH = 'RESULTS_PUSH'
export const RESULTS_CLEAR = 'RESULTS_CLEAR'
export const RESULTS_CHANGED = 'RESULTS_CHANGED'

// Dashboard

export const SOCKET_TILES = 'SOCKET_TILES'
export const SOCKET_TILES_UPDATE_ONE = 'SOCKET_TILES_UPDATE_ONE'

// Home Charts

export const SOCKET_CHARTS_UPDATE_ONE = 'SOCKET_CHARTS_UPDATE_ONE'
export const SOCKET_CHART_CHANGED = 'SOCKET_CHART_CHANGED'

// Configs

export const SOCKET_CONFIGS = 'SOCKET_CONFIGS'
export const SOCKET_CONFIGS_UPDATE_ONE = 'SOCKET_CONFIGS_UPDATE_ONE'

// Build

export const SOCKET_BUILD = 'SOCKET_BUILD'

// Time sync

export const SOCKET_TIME_SYNC = 'SOCKET_TIME_SYNC'
