export const TOGGLE_DEVICE = 'TOGGLE_DEVICE'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const EXPAND_MENU = 'EXPAND_MENU'

export const SWITCH_EFFECT = 'SWITCH_EFFECT'

// Results

export const RESULTS_PUSH = 'RESULTS_PUSH'
export const RESULTS_CLEAR = 'RESULTS_CLEAR'
export const RESULTS_CHANGED = 'RESULTS_CHANGED'

// Tiles

export const SOCKET_TILES = 'SOCKET_TILES'
export const SOCKET_TILES_UPDATE_ONE = 'SOCKET_TILES_UPDATE_ONE'

// Integrations

export const SOCKET_INTEGRATIONS = 'SOCKET_INTEGRATIONS'
export const SOCKET_INTEGRATIONS_UPDATE_ONE = 'SOCKET_INTEGRATIONS_UPDATE_ONE'
export const SOCKET_INTEGRATIONS_DELETE = 'SOCKET_INTEGRATIONS_DELETE'

// Home Links

export const SOCKET_HOMELINKS = 'SOCKET_HOMELINKS'
export const SOCKET_HOMELINKS_UPDATE_ONE = 'SOCKET_HOMELINKS_UPDATE_ONE'
export const SOCKET_HOMELINKS_DELETE = 'SOCKET_HOMELINKS_DELETE'

// Stages

export const SOCKET_STAGES = 'SOCKET_STAGES'
export const SOCKET_STAGES_UPDATE_ONE = 'SOCKET_STAGES_UPDATE_ONE'
export const SOCKET_STAGES_DELETE = 'SOCKET_STAGES_DELETE'

// Home Links

export const SOCKET_USERS = 'SOCKET_USERS'
export const SOCKET_USERS_UPDATE_ONE = 'SOCKET_USERS_UPDATE_ONE'
export const SOCKET_USERS_DELETE = 'SOCKET_USERS_DELETE'

// Users

export const SOCKET_CHARTS_UPDATE_ONE = 'SOCKET_CHARTS_UPDATE_ONE'
export const SOCKET_CHART_CHANGED = 'SOCKET_CHART_CHANGED'

// Configs

export const SOCKET_CONFIGS = 'SOCKET_CONFIGS'
export const SOCKET_CONFIGS_UPDATE_ONE = 'SOCKET_CONFIGS_UPDATE_ONE'
export const SOCKET_CONFIGS_DELETE = 'SOCKET_CONFIGS_DELETE'
export const CONFIGS_UPDATE_SORTING = 'CONFIGS_UPDATE_SORTING'

// Build

export const SOCKET_BUILD = 'SOCKET_BUILD'

// Time sync

export const SOCKET_TIME_SYNC = 'SOCKET_TIME_SYNC'

// Auth

export const SET_AUTH = 'SET_AUTH'
